# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8.0.322
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.322'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file.
    
    - name: current location and direcroty details
      run : pwd && ls -l
      shell : bash
    
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - run: mkdir staging && cp /home/runner/work/java-app/java-app/target/*.war staging
    - name: Artifact for Java
      uses: actions/upload-artifact@v1 
      with:
        name: Package
        path: staging

    - name: Copy war file from github
      run : ls -Rl .github/
      shell : bash

    - name: Copy war file from github
      run : sh .github/workflows/github-actions-script.sh
      shell : bash
    
